// smoke_fakenect (big-fix-two T0.4): the whole capture path, end to end, with
// the REAL sensor code: PipelineController::start() -> KinectSensor ->
// libfreenect API -> libfakenect (LD_PRELOAD) replaying a dump generated by
// make_fake_dump from the synthetic room with real Kinect timestamp behaviour.
// This is the test that would have caught c311c69: with the old microsecond
// timestamp unit nothing pairs (verified: 117 of 118 frames depth-only).
//
// Asserts over ~4 s: capture >= 25 fps, integrated >= 8 fps, tracking never
// lost, frames are paired with RGB, no sensor stall, stop() < 500 ms, and a
// non-empty mesh exports after stop.
#include "app/PipelineController.h"

#include <chrono>
#include <cstdio>
#include <cstdlib>
#include <string>
#include <thread>

namespace {
int g_failures = 0;
int g_checks   = 0;
#define CHECK(cond, what)                                                        \
    do {                                                                         \
        ++g_checks;                                                              \
        if (!(cond)) {                                                           \
            std::printf("FAIL: %s  [%s:%d]\n", std::string(what).c_str(),        \
                        __FILE__, __LINE__);                                     \
            ++g_failures;                                                        \
        }                                                                        \
    } while (false)
}  // namespace

int main(int argc, char** argv) {
    if (!std::getenv("FAKENECT_PATH") || !std::getenv("LD_PRELOAD")) {
        std::printf("smoke_fakenect: SKIP (needs FAKENECT_PATH and LD_PRELOAD=libfakenect)\n");
        return 77;
    }
    const std::string out = argc > 1 ? argv[1] : "smoke_fakenect.ply";
    using namespace std::chrono;
    using kfusion::app::PipelineState;

    kfusion::app::PipelineController pc(kfusion::sensor::PreprocessBackend::CPU);
    CHECK(pc.start(), "start() opens the (fake) Kinect");

    std::this_thread::sleep_for(1s);   // warm-up: first model, rate window
    const auto m0 = pc.metricsSnapshot();
    int lost = 0;
    for (int i = 0; i < 30; ++i) {
        std::this_thread::sleep_for(100ms);
        if (pc.metricsSnapshot().state == PipelineState::TrackingLost) ++lost;
    }
    const auto m1 = pc.metricsSnapshot();
    const float secs = 3.0f;
    const float integrated_fps = (m1.integrated_frames - m0.integrated_frames) / secs;
    std::printf("  capture %.1f fps, integrated %.1f fps, lost %d, depth cb %llu, rgb cb %llu, "
                "depth-only %llu, stalled %d\n",
                m1.capture_fps, integrated_fps, lost,
                static_cast<unsigned long long>(m1.sensor_depth_callbacks),
                static_cast<unsigned long long>(m1.sensor_rgb_callbacks),
                static_cast<unsigned long long>(m1.sensor_depth_only), m1.sensor_stalled);
    CHECK(m1.capture_fps >= 25.0f, "capture >= 25 fps");
    CHECK(integrated_fps >= 8.0f, "integrated >= 8 fps");
    CHECK(lost == 0, "tracking never lost");
    CHECK(!m1.sensor_stalled, "no sensor stall");
    CHECK(m1.sensor_depth_callbacks > 60, "depth callbacks arrived");
    CHECK(m1.sensor_depth_only * 10 < m1.sensor_depth_callbacks,
          "at least 90% of depth frames paired with RGB");

    const auto t0 = steady_clock::now();
    pc.stop();
    const double stop_ms = duration<double, std::milli>(steady_clock::now() - t0).count();
    std::printf("  stop %.0f ms\n", stop_ms);
    CHECK(stop_ms < 500.0, "stop() < 500 ms");
    CHECK(pc.exportPLY(out), "a mesh exports after stop");

    if (g_failures == 0) {
        std::printf("smoke_fakenect: PASS (%d checks)\n", g_checks);
        return 0;
    }
    std::printf("smoke_fakenect: FAIL (%d failed checks)\n", g_failures);
    return 1;
}
